version: '2'

services:
    postgres:
        hostname: postgres
        image: postgres:9.6
        volumes:
            - .docker/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        expose:
          - "5432"
    packagist:
        image: okvpn/packagist:1.0
        container_name: private-packagist
        hostname: pkg
        volumes:
          - .docker/redis:/var/lib/redis
          - .docker/tmp/www-composer:/var/www/.composer
          - .ssh:/var/tmp/ssh
        links:
          - "postgres"
        environment:
          PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
          VIRTUAL_HOST: ${APP_HOST}
          DATABASE_HOST: ${DATABASE_HOST}
          DATABASE_PORT: ${DATABASE_PORT}
          DATABASE_DRIVER: ${DATABASE_DRIVER}
          DATABASE_USER: ${DATABASE_USER}
          DATABASE_NAME: ${DATABASE_NAME}
          DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        ports:
          - 127.0.0.1:8088:80
