version: '2'

services:
    postgres:
        hostname: postgres
        container_name: postgres_packagist
        image: postgres:9.6
        volumes:
            - .docker/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: packagist
            POSTGRES_PASSWORD: 123456
        expose:
            - "5432"
    packagist:
        build:
            context: .
            args:
                VERSION: master
                CACHEBUST: ~
        image: okvpn/packagist:lasted
        container_name: packagist
        hostname: packagist
        volumes:
            - .docker/data:/var/tmp/data
            - .docker/redis:/var/lib/redis
            - .docker/zipball:/var/www/packagist/app/zipball
            - .docker/composer:/var/www/.composer
            - .docker/ssh:/var/www/.ssh
        links:
            - "postgres"
        environment:
            PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
            VIRTUAL_HOST: packagist.mycompany.org
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_DRIVER: pdo_pgsql
            DATABASE_USER: postgres
            DATABASE_NAME: packagist
            DATABASE_PASSWORD: 123456
            ADMIN_USER: admin
            ADMIN_PASSWORD: admin
            ADMIN_EMAIL: admin@example.com
        ports:
          - 8088:80
