parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_name: packagist
    database_user: postgres
    database_password: ~
    database_port: ~
    database_name_test: packagist_test

    mailer_transport:
    mailer_host: localhost
    mailer_user:
    mailer_password:
    mailer_from_email: admin@example.org
    mailer_from_name: Admin Team
    mailer_encryption: tls
    mailer_port: ~
    mailer_auth_mode: login

    redis_dsn: redis://localhost/1
    redis_dsn_test: redis://127.0.0.1/14
    redis_session_dsn: redis://localhost/2

    locale: en

    # -- performance features --
    # set both to apc to optimize things if it is available
    validation_cache_backend: ~
    doctrine_cache_backend: array

    # -- security features --
    secret: CHANGE_ME_IN_PROD
    remember_me.secret: CHANGE_ME_IN_PROD

    # set to true to enforce ssl, make sure you have a proper certificate in place
    force_ssl: false
    # e.g. [127.0.0.1] if the app is running behind a reverse proxy on localhost
    trusted_proxies: ~
    # e.g. ['.*\.?packagist\.org$'] to allow packagist.org and all subdomains as valid hosts
    trusted_hosts: ~

    # Host for download zip
    packagist_dist_host: local.dev
